package ar.edu.unlu.molino195157.Modelo.Enums;

public enum Eventos {
    COMIENZO,
    INGRESOFICHAJUGADOR1,
    JUGADOR1MOLINO,
    INGRESOFICHAJUGADOR2,
    JUGADOR2MOLINO,
    CANTIDADFICHASRESTANTES,
    EMPIEZASEGUNDAFASE,
    MUEVEJUGADOR1SELECCION,
    MUEVEJUGADOR2SELECCION,
    MUEVEJUGADOR1CASILLA,
    MUEVEJUGADOR2CASILLA,
    GANADORJUGADOR2,
    GANADORJUGADOR1
}
